version: "3"
services:
  db_container:
    build: ../L2E4/.
    command: --default-authentication-plugin=mysql_native_password
  web:
    build: ../L2E2/.
    ports:
      - "4000:80"
    depends_on:
      - db
